// This file is @generated by prost-build.
/// SubgraphIndexingAgreementEvent is the envelope that wraps all subgraph indexing agreement event types.
///
/// Provides:
///   - event_id -> unique identifier (uuid)
///   - event_type -> event type discrimination
///   - event_version -> versioning for schema evolution awareness to the consumer
///   - timestamp -> when the event occurred, useful for ordering/debugging
///   - subgraph_deployment_qm_hash -> Qm hash of the Subgraph deployment
///   - the_graph_network -> CAIP-2 chain id of The Graph protocol network the Subgraph Deployment is published to (e.g. eip155:42161)
///   - payload -> the event payload, determined by the event_type
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubgraphIndexingAgreementEvent {
    /// Unique event identifier.
    /// Format: UUID v7 (time-ordered) for natural chronological sorting.
    /// Example: "01912345-6789-7abc-def0-123456789abc"
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    /// Event type discriminator for routing and filtering.
    /// Values: "subgraph.indexing.agreement.request.received", "subgraph.indexing.agreement.proposed", "subgraph.indexing.agreement.accepted", "subgraph.indexing.agreement.request.expired", "subgraph.indexing.agreement.n_indexers_unavailable", "subgraph.indexing.agreement.terminated"
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// Schema version for forward compatibility.
    /// Consumers should handle unknown fields gracefully.
    /// Current version: "1.0"
    #[prost(string, tag = "3")]
    pub event_version: ::prost::alloc::string::String,
    /// Event timestamp in RFC 3339 format.
    /// Example: "2024-01-15T10:30:00.123Z"
    #[prost(string, tag = "4")]
    pub timestamp: ::prost::alloc::string::String,
    /// Qm hash of the Subgraph deployment with a submitted indexing agreement event.
    #[prost(string, tag = "5")]
    pub subgraph_deployment_qm_hash: ::prost::alloc::string::String,
    /// CAIP-2 chain id of The Graph protocol network where the Subgraph was published to.
    /// Format: "eip155:{chain_id}". Examples: "eip155:42161" (arbitrum), "eip155:421614" (arbitrum-sepolia)
    #[prost(string, tag = "6")]
    pub the_graph_network: ::prost::alloc::string::String,
    /// Event payload - exactly one of the specific event types.
    /// Use event_type field to determine which payload is present.
    #[prost(
        oneof = "subgraph_indexing_agreement_event::Payload",
        tags = "7, 8, 9, 10, 11, 12"
    )]
    pub payload: ::core::option::Option<subgraph_indexing_agreement_event::Payload>,
}
/// Nested message and enum types in `SubgraphIndexingAgreementEvent`.
pub mod subgraph_indexing_agreement_event {
    /// Event payload - exactly one of the specific event types.
    /// Use event_type field to determine which payload is present.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "7")]
        SubgraphIndexingAgreementRequestReceived(
            super::SubgraphIndexingAgreementRequestReceived,
        ),
        #[prost(message, tag = "8")]
        SubgraphIndexingAgreementProposed(super::SubgraphIndexingAgreementProposed),
        #[prost(message, tag = "9")]
        SubgraphIndexingAgreementAccepted(super::SubgraphIndexingAgreementAccepted),
        #[prost(message, tag = "10")]
        SubgraphIndexingAgreementRequestExpired(
            super::SubgraphIndexingAgreementRequestExpired,
        ),
        #[prost(message, tag = "11")]
        SubgraphIndexingAgreementNIndexersUnavailable(
            super::SubgraphIndexingAgreementNIndexersUnavailable,
        ),
        #[prost(message, tag = "12")]
        SubgraphIndexingAgreementTerminated(super::SubgraphIndexingAgreementTerminated),
    }
}
/// SubgraphIndexingAgreementRequestReceived is emitted when a Subgraph developer submits a request to the dipper to find
/// indexers to index the given Subgraph.
///
/// Event type: subgraph.indexing.agreement.request.received
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubgraphIndexingAgreementRequestReceived {
    /// Number of indexing agreements requested by the Subgraph developer.
    #[prost(int32, tag = "1")]
    pub agreements_requested: i32,
}
/// SubgraphIndexingAgreementProposed is emitted once the dipper has gone to the IISA, received candidates (indexers),
/// sent gRPC offers to these candidates, but before any candidate has accepted onchain
///
/// Event type: subgraph.indexing.agreement.proposed
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubgraphIndexingAgreementProposed {
    /// 0x addresses of the Indexer candidates dipper sent agreement offers to in
    /// this proposal round (the IISA-selected indexers newly proposed this cycle).
    #[prost(string, repeated, tag = "1")]
    pub candidates: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Timestamp of when the request expires
    #[prost(uint64, tag = "2")]
    pub request_expires_at: u64,
}
/// SubgraphIndexingAgreementAccepted is emitted when an Indexer candidate has accepted onchain the Subgraph indexing request.
///
/// Event type: subgraph.indexing.agreement.accepted
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubgraphIndexingAgreementAccepted {
    /// 0x hex of the on-chain agreement id (bytes16) that was accepted.
    /// Stable, unique per agreement -- consumers dedup on (agreement_id, event_type)
    /// since emission is at-least-once (an accepted event may be redelivered).
    #[prost(string, tag = "6")]
    pub agreement_id: ::prost::alloc::string::String,
    /// 0x address of the Indexer who accepted the indexing agreement
    #[prost(string, tag = "1")]
    pub indexer: ::prost::alloc::string::String,
    /// Timestamp of when the agreement was accepted
    #[prost(uint64, tag = "2")]
    pub accepted_at: u64,
    /// 0x Hex of the onchain transaction for the accepted indexing agreement
    #[prost(string, tag = "3")]
    pub accepted_tx: ::prost::alloc::string::String,
    /// Timestamp of when the agreement is scheduled to end
    #[prost(uint64, tag = "4")]
    pub ends_at: u64,
    /// 0x address of the payer
    #[prost(string, tag = "5")]
    pub payer: ::prost::alloc::string::String,
}
/// SubgraphIndexingAgreementRequestExpired is emitted when an Indexer candidate fails to accept within the provided time limit
///
/// Event type: subgraph.indexing.agreement.request.expired
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubgraphIndexingAgreementRequestExpired {
    /// 0x hex of the on-chain agreement id (bytes16) that expired.
    /// Stable, unique per agreement -- consumers dedup on (agreement_id, event_type)
    /// since emission is at-least-once (an expired event may be redelivered).
    #[prost(string, tag = "4")]
    pub agreement_id: ::prost::alloc::string::String,
    /// 0x address of the Indexer who failed to accept the agreement within the given time limit
    #[prost(string, tag = "1")]
    pub indexer: ::prost::alloc::string::String,
    /// Timestamp of when the Indexing agreement was proposed
    #[prost(uint64, tag = "2")]
    pub request_proposed_at: u64,
    /// Timestamp of when the required expired
    #[prost(uint64, tag = "3")]
    pub request_expired_at: u64,
}
/// SubgraphIndexingAgreementNIndexersUnavailable is emitted when the IISA selection returns fewer Indexer candidates than requested
///
/// Event type: subgraph.indexing.agreement.n_indexers_unavailable
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubgraphIndexingAgreementNIndexersUnavailable {
    /// Number of indexing agreements requested by the Subgraph developer.
    #[prost(int32, tag = "1")]
    pub agreements_requested: i32,
    /// Number of indexer candidates selected by the IISA
    #[prost(int32, tag = "2")]
    pub candidates_returned: i32,
}
/// SubgraphIndexingAgreementTerminated is emitted if either the Subgraph developer, or Indexer, cancel the agreement
///
/// Event type: subgraph.indexing.agreement.terminated
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubgraphIndexingAgreementTerminated {
    /// 0x hex of the on-chain agreement id (bytes16) that was terminated.
    /// Stable, unique per agreement -- consumers dedup on (agreement_id, event_type)
    /// since emission is at-least-once (a terminated event may be redelivered).
    #[prost(string, tag = "6")]
    pub agreement_id: ::prost::alloc::string::String,
    /// 0x address of the Indexer that had the accepted agreement that was terminated
    #[prost(string, tag = "1")]
    pub indexer: ::prost::alloc::string::String,
    /// Timestamp of when the Indexing Agreement was terminated
    #[prost(uint64, tag = "2")]
    pub terminated_at: u64,
    /// 0x address of the entity (developer, indexer, etc) that terminated the agreement
    #[prost(string, tag = "3")]
    pub terminated_by: ::prost::alloc::string::String,
    /// 0x hex of the onchain transaction of the agreement cancellation
    #[prost(string, tag = "4")]
    pub terminated_tx: ::prost::alloc::string::String,
    /// Count of remaining active (accepted) agreements on the Subgraph, excluding
    /// the one just terminated.
    /// 0  -> the Subgraph no longer has any active, accepted indexing agreements.
    /// -1 -> the count was unavailable when the event was emitted (e.g. a transient
    ///        datastore error); treat as unknown, not as zero.
    #[prost(int32, tag = "5")]
    pub remaining_accepted_indexing_agreements: i32,
}
