// This file is @generated by prost-build.
/// SubgraphIndexingRequestEvent is the envelope that wraps all the Subgraph Indexing Request event types.
///
/// Provides:
///   - event_id -> unique identifier (uuid)
///   - event_type -> event type discrimination
///   - event_version -> versioning for schema evolution awareness to the consumer
///   - timestamp -> when the event occurred, useful for ordering/debugging
///   - subgraph_deployment_qm_hash -> Qm hash of the Subgraph deployment
///   - the_graph_network_caip2id -> CAIP-2 chain id of The Graph protocol network the Subgraph Deployment is published to (e.g. eip155:42161)
///   - payload -> the event payload, determined by the event_type
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubgraphIndexingRequestEvent {
    /// Unique event identifier.
    /// Format: UUID v7 (time-ordered) for natural chronological sorting.
    /// Example: "01912345-6789-7abc-def0-123456789abc"
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    /// Event type discriminator for routing and filtering.
    /// Values: "subgraph.indexing.request.propose", "subgraph.indexing.agreements.terminate"
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// Schema version for forward compatibility.
    /// Consumers should handle unknown fields gracefully.
    /// Current version: "1.0"
    #[prost(string, tag = "3")]
    pub event_version: ::prost::alloc::string::String,
    /// Event timestamp in RFC 3339 format.
    /// Example: "2024-01-15T10:30:00.123Z"
    #[prost(string, tag = "4")]
    pub timestamp: ::prost::alloc::string::String,
    /// Qm hash of the Subgraph deployment with a submitted indexing agreement event.
    #[prost(string, tag = "5")]
    pub subgraph_deployment_qm_hash: ::prost::alloc::string::String,
    /// CAIP-2 chain id of The Graph protocol network where the Subgraph was published to.
    /// Format: "eip155:{chain_id}". Examples: "eip155:42161" (arbitrum), "eip155:421614" (arbitrum-sepolia)
    #[prost(string, tag = "6")]
    pub the_graph_network_caip2id: ::prost::alloc::string::String,
    /// Event payload - exactly one of the specific event types.
    /// Use event_type field to determine which payload is present.
    #[prost(oneof = "subgraph_indexing_request_event::Payload", tags = "7")]
    pub payload: ::core::option::Option<subgraph_indexing_request_event::Payload>,
}
/// Nested message and enum types in `SubgraphIndexingRequestEvent`.
pub mod subgraph_indexing_request_event {
    /// Event payload - exactly one of the specific event types.
    /// Use event_type field to determine which payload is present.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "7")]
        SubgraphIndexingRequestPropose(super::SubgraphIndexingRequestPropose),
    }
}
/// SubgraphIndexingRequestPropose is emitted when the Subgraph developer initiates a request to have the Subgraph indexed
///
/// Event type: subgraph.indexing.request.propose
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubgraphIndexingRequestPropose {
    /// Number of requested Indexing agreements to find
    #[prost(int32, tag = "1")]
    pub indexing_agreements_requested: i32,
    /// CAIP-2 chain id of the network the Subgraph indexes (its data source),
    /// distinct from the_graph_network_caip2id on the envelope.
    /// Format: "eip155:{chain_id}". Example: "eip155:1" for a subgraph indexing Ethereum mainnet.
    #[prost(string, tag = "2")]
    pub indexed_network_caip2id: ::prost::alloc::string::String,
}
